### ISSUE TITLE
Cannot invoke "net.minecraft.world.level.dimension.LevelStem.f_63976_()" because "levelStem" is null

### ISSUE THREAD

**Issue by iwandaugnujrgeis** [Lyof429/EndsPhantasm#24]
Hi! Whenever I try to create a new world in my custom modpack — my game crashes with this error:

```
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.dimension.LevelStem.f_63976_()" because "levelStem" is null
	at net.lyof.phantasm.world.biome.surface.ModMaterialRules.addModMaterialRules(ModMaterialRules.java:141) ~[phantasm-0.4.2.jar%23689!/:net.lyof.phantasm] {re:classloading}
	at net.lyof.phantasm.world.biome.surface.__ModMaterialRules_addModMaterialRules_ServerAboutToStartEvent.invoke(.dynamic) ~[phantasm-0.4.2.jar%23689!/:net.lyof.phantasm] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:98) ~[forge-1.20.1-47.3.0-universal.jar%23776!/:?] {re:classloading}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23771!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23771!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23771!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}

**Comment by iwandaugnujrgeis** [comment]
[crash-2024-12-08_23.36.26-server.txt](https://github.com/user-attachments/files/18054295/crash-2024-12-08_23.36.26-server.txt)

**Comment by SashaKYotoz** [comment]
Could you send latest log file and your modlist too? Whereas something rewriting access to registry of End dimension

**Comment by iwandaugnujrgeis** [comment]
Hi! 

Just tried it again with some updated mods and crashed again! 

[latest.log](https://github.com/user-attachments/files/18137926/latest.log)

Modlist inside of the crash report. I don't think I have anything that tinkers with the End though. It's really a bummer because your mod looks great!

[crash-2024-12-14_23.08.06-server.txt](https://github.com/user-attachments/files/18137927/crash-2024-12-14_23.08.06-server.txt)

**Comment by SashaKYotoz** [comment]
According to latest.log BiomeReplacer mod causes this error by replacing vanilla level stem and NoiseBasedChunkGenerato

**Comment by SashaKYotoz** [comment]
in WIP version of EP was added extra condition to avoid crash of Minecraft, but biomes most likely won't be spawn in case with BiomeReplacer mod on

**Comment by iwandaugnujrgeis** [comment]
Thank you, it actually was BiomeReplacer! I'm really happy I can play your mod now!
